name: Backend_pipeline

on: [push]

jobs:
  test:
    name: Check code behaviors (test)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: ["7.4"]
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-version }}
    - name: Install dependencies
      run: (cd backend && composer install --no-interaction --no-progress --ansi)
    - name: Create auto-loader
      run : (cd backend && composer dump-autoload)
    - name: Unit tests
      run: backend/vendor/bin/phpunit --testdox --coverage-clover=backend/coverage/coverage.xml -c backend/tests/phpunit.xml
    - name: Store coverage datas
      uses: actions/upload-artifact@v2
      with:
        name: coverageFolder
        path: backend/coverage

  coverage:
    name: Upload coverage to Codecov (coverage)
    runs-on: ubuntu-latest
    needs:
      - test
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Download coverage datas
        uses: actions/download-artifact@v2
        with:
          name: coverageFolder
          path: backend/coverage
      - name : Upload coverage report
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: backend/coverage/coverage.xml